services:
  - type: web
    name: stock-crawler
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PORT
        value: 8888
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
